#!/bin/bash

help() {
  echo "Usage:"
  echo "  zmicro package install jabba <args...>"
  echo ""
}

core() {
  if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    help
    exit 0
  fi

  log::info "installing jabba ..."

  #  [ -s "$JABBA_HOME/jabba.sh" ] && source "$JABBA_HOME/jabba.sh"

  export JABBA_HOME="$HOME/.jabba"
  export JABBA_ENV="$JABBA_HOME/jabba.sh"
  export JABBA_SHELL_INTEGRATION=ON
  export PATH=$JABBA_HOME/bin:$PATH

  command -v jabba >>/dev/null 2>&1
  if [ "$?" != "0" ]; then
    os::curl https://github.com/shyiko/jabba/raw/master/install.sh | bash && . $JABBA_ENV
  fi

  log::success "install jabba success."
}

run() {
  core $@
}

run $@
